# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

workspace 'hanashitai.xcworkspace'
project 'hanashitai.xcodeproj'
project 'preprocess/preprocess.xcodeproj'

use_frameworks!
inhibit_all_warnings!

target 'hanashitai' do
  platform :ios, '10.0'
  project 'hanashitai.xcodeproj'
  pod 'Alamofire',               '4.8.2'
  pod 'Charts',                  '3.2.1'
  pod 'SQLite.swift'
  pod 'PromisesSwift'
  pod 'Firebase/Analytics'
  pod 'Firebase/Performance'
  pod 'Firebase/Crashlytics'
  pod 'RealmSwift'
end

target 'preprocess' do
  platform :osx, '10.15'
  project 'preprocess/preprocess.xcodeproj'
  pod 'SwiftSyllables', :git => "git@github.com:wangchou/SwiftSyllables.git"
  pod 'Alamofire', '4.8.2'
  pod 'PromisesSwift'
  pod 'SQLite.swift'
  pod 'RealmSwift'
end

# https://github.com/CocoaPods/CocoaPods/issues/3707#issuecomment-354754864
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name =~ /-macOS$/ or target.name == 'SwiftSyllables'
      target.build_configurations.each do |config|
        config.build_settings['DYLIB_INSTALL_NAME_BASE'] = target.product_name
        config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'YES'
      end
    end

    # https://github.com/CocoaPods/CocoaPods/issues/9884#issuecomment-698811522
    target.build_configurations.each do |bc|
        if bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] == '8.0'
            bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '10.0'
        end
    end

    # handle non mac catalyst lib
    # https://stackoverflow.com/a/63559134/2797799
    libs = ["FirebaseAnalytics", "FirebasePerformance", "FIRAnalyticsConnector", "GoogleAppMeasurement"]

    target.build_configurations.each do |config|
        xcconfig_path = config.base_configuration_reference.real_path
        xcconfig = File.read(xcconfig_path)
        values = ""

        libs.each { |lib|
            if xcconfig["-framework \"#{lib}\""]
                puts "Found '#{lib}' on target '#{target.name}'"
                xcconfig.sub!(" -framework \"#{lib}\"", '')
                values += " -framework \"#{lib}\""
            end
        }

        if values.length > 0
            puts "Preparing '#{target.name}' for Catalyst\n\n"
            new_xcconfig = xcconfig + 'OTHER_LDFLAGS[sdk=iphone*] = $(inherited)' + values
            File.open(xcconfig_path, "w") { |file| file << new_xcconfig }
        end
    end
  end
end
