# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '10.0'

use_frameworks!
inhibit_all_warnings!

target 'hanashitai' do
  pod 'Alamofire'
  pod 'Charts',                  '3.2.1'
  pod 'SQLite.swift'
  pod 'PromisesSwift'
  pod 'Firebase/Analytics'
  pod 'Firebase/Performance'
  pod 'Fabric', '~> 1.10.2'
  pod 'Crashlytics', '~> 3.13.4'
end
